byod:
  ray_ecr: rayproject
  ray_cr_repo: ray
  ray_ml_cr_repo: ray-ml
  byod_ecr: 029272617770.dkr.ecr.us-west-2.amazonaws.com
  aws_cr: 029272617770.dkr.ecr.us-west-2.amazonaws.com
  gcp_cr: us-west1-docker.pkg.dev/anyscale-oss-ci
state_machine:
  aws_bucket: ray-ci-results
credentials:
  aws2gce: release/aws2gce_iam.json
pipeline:
  premerge:
    - 0189942e-0876-4b8f-80a4-617f988ec59b
  postmerge: 
    - 0189e759-8c96-4302-b6b5-b4274406bf89
    - 018e0f94-ccb6-45c2-b072-1e624fe9a404
